# docker-compose.yml

version: "3.9"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: orders_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
