# docker-compose.yml

version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: orders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
