"""Add default roles data

Revision ID: 98965b3aa26a
Revises: ca1ed7b81174
Create Date: 2025-07-16 15:53:42.665230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98965b3aa26a'
down_revision: Union[str, Sequence[str], None] = 'ca1ed7b81174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Insert default roles
    op.execute(
        "INSERT INTO roles (role_id, name, `key`, description) VALUES "
        "(1, 'Administrator', 'admin', 'Full system access with all permissions'), "
        "(2, 'Customer', 'customer', 'Limited access for customer operations')"
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove default roles
    op.execute("DELETE FROM roles WHERE `key` IN ('admin', 'customer')")
    
    # ### end Alembic commands ###
